### ISSUE TITLE
predeletion hooks for previous releases

### ISSUE THREAD

**Issue by ivar** [leehambley/capistrano-handbook#4]
My rails app uses a third party assethost to store all the static files. When I do a cleanup, the appropriate release is deleted from the releases folder, but the assethost files remain on the remote server. 
I'm wondering if there is a mechanism by which I can trigger a callback for each release folder that is to be deleted.

**Comment by leehambley** [comment]
you can hook this on deploy:cleanup using before/after filters, and use the same mechanism by which your files get on to assethost(?) to remove them?
